CREATE TABLE food
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255),
    categoria  SMALLINT,
    quantidade INT,
    validade   TIMESTAMP,
    CONSTRAINT pk_food PRIMARY KEY (id)
);